name: myfoodtracker
description: Applicatione per la gestione della spesa.
publish_to: 'none'
private: true

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5
  firebase_core: ^2.17.0
  firebase_analytics: ^10.5.1
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  firebase_crashlytics: ^3.3.7
  firebase_in_app_messaging: ^0.7.3+7
  firebase_performance: ^0.9.2+7
  firebase_remote_config: ^4.2.7
  dependency_validator: ^3.0.0
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  lite_rolling_switch: ^1.0.0
  fluttertoast: ^8.1.1
  clipboard: ^0.1.3
  readmore: ^2.2.0
  enhance_stepper: ^0.1.1
  another_stepper: ^1.1.6
  ##  image_picker:
  #  image_picker: any
  flutter_switch: ^0.3.2
  flutter_slidable: any
  get_storage: ^2.0.3
  dotted_border: ^2.0.0+3
  openfoodfacts: ^3.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
  fonts:
    - family: AirbnbCereal_W_Bd
      fonts:
        - asset: assets/font/AirbnbCereal_W_Bd.otf
          style: italic
    - family: AirbnbCereal_W_Bk
      fonts:
        - asset: assets/font/AirbnbCereal_W_Bk.otf
          style: italic
    - family: AirbnbCereal_W_Md
      fonts:
        - asset: assets/font/AirbnbCereal_W_Md.otf
          style: italic
