name: Flutter test
run-name: Inizio test Flutter
on: [push]
jobs:
  Flutter-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'oracle'
          java-version: '17'
      - run: echo "Installato java."
      - uses: subosito/flutter-action@v2
      - run: echo "Installato flutter."
      - run: flutter pub get
      - run: echo "Installate dependency di Flutter."
      - run: flutter build apk
      - run: echo "Costruito apk android."
      - run: flutter build appbundle
      - run: echo "Terminato correttamente."
